name: Unit Tests
permissions: { }

on:
  pull_request:
    types: [ reopened ]
  push:

env:
  PY_BASE_VERSION: "3.10"

jobs:
  coverage-test: # Tests code for base version and coverage
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/test-setup
        with:
          python-version: ${{ env.PY_BASE_VERSION }}

      - name: Run tests with coverage and enforce minimum
        run: pytest -x --cov --cov-report=xml

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  macos-test: # Tests on macOS latest
    needs: coverage-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/test-setup
        with:
          python-version: ${{ env.PY_BASE_VERSION }}
      - name: Run Tests
        run: pytest -x

  version-tests: # Tests code for higher version in ubuntu
    needs: coverage-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.11", "3.12","3.13" ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/test-setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: pytest -x
